import { Header } from "@/Components/header/Header";
import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import StyledContent from "./style";

const noto_sans_kr = Noto_Sans_KR({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
});

export const metadata: Metadata = {
  title: "청운중학교 통합 알리미",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={noto_sans_kr.className}>
        <StyledContent >
          <Header />
          {children}
        </StyledContent>
      </body>
    </html>
  );
}
